---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: game
          image: lloyddigital/gameapp:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          protocol: TCP
          resources: 
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      imagePullSecrets:
        - name: docker
      restartPolicy: Always
      volumes:
        - name: cache-volume
          emptyDir:
            sizeLimit: 500Mi
        
---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
