apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
        - name: game-app
          image: lloyddigital/gameapp:${TAG}   # Use your actual Docker image name and tag
          ports:
            - containerPort: 3000
          resources:
          limits:
            cpu: "800m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"  

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game-app
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service within the cluster
      targetPort: 3000  # The port your React app is listening on inside the pod
  type: LoadBalancer