apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app
  namespace: dev
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        image: lloyddigital/gameapp:${TAG}  
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: "800m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "256Mi"
        imagePullPolicy: Always
      resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "100Mi"
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  selector:
    app: game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP